package com.fastfood.yourwaysandwich.model.service;

/**
 * Types of responses expected when calling Your Way API services
 */
public enum ResponseType {

    MENU,
    SANDWICH_INGREDIENTS,
    SANDWICH_DETAILS,
    AVAILABLE_INGREDIENTS,
    ORDERED_SANDWICH,
    ORDERED_CUSTOM_SANDWICH,
    PROMOTIONS,
    CART,
    MENU_ERROR,
    SANDWICH_INGREDIENTS_ERROR,
    SANDWICH_DETAILS_ERROR,
    AVAILABLE_INGREDIENTS_ERROR,
    ORDERED_SANDWICH_ERROR,
    ORDERED_CUSTOM_SANDWICH_ERROR,
    PROMOTIONS_ERROR,
    CART_ERROR
}